addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/1.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'grassgrn256')
engineApplyShaderToWorldTexture(shader, 'brngrss2stonesb')
engineApplyShaderToWorldTexture(shader, 'grass128hv_blend_')
engineApplyShaderToWorldTexture(shader, 'sfn_rockgrass1')
engineApplyShaderToWorldTexture(shader, 'sfn_rock2')
engineApplyShaderToWorldTexture(shader, 'golf_fairway2')
engineApplyShaderToWorldTexture(shader, 'veg_bevtreebase')
engineApplyShaderToWorldTexture(shader, 'lodgrass_128hv')
engineApplyShaderToWorldTexture(shader, 'desgrassbrnsnd')
engineApplyShaderToWorldTexture(shader, 'sfn_rockgrass10')
engineApplyShaderToWorldTexture(shader, 'ws_football_lines2')
engineApplyShaderToWorldTexture(shader, 'bow_church_dirt_to_grass_side_t')
engineApplyShaderToWorldTexture(shader, 'sandstonemixb')
engineApplyShaderToWorldTexture(shader, 'grasspatch_64hv')
engineApplyShaderToWorldTexture(shader, 'desmuddesgrsblend_sw')
engineApplyShaderToWorldTexture(shader, 'grasstype7')
engineApplyShaderToWorldTexture(shader, 'grasspave256')
engineApplyShaderToWorldTexture(shader, 'trainground1')
engineApplyShaderToWorldTexture(shader, 'scumtiles3_lae')
engineApplyShaderToWorldTexture(shader, 'grassgrnbrnx256')
engineApplyShaderToWorldTexture(shader, 'forestfloorblendb')
engineApplyShaderToWorldTexture(shader, 'forestfloor256mudblend')
engineApplyShaderToWorldTexture(shader, 'hiwayinsideblend1_256')
engineApplyShaderToWorldTexture(shader, 'greyground2sand')
engineApplyShaderToWorldTexture(shader, 'grassdirtblend')
engineApplyShaderToWorldTexture(shader, 'ws_patchygravel')
engineApplyShaderToWorldTexture(shader, 'grasstype4_staw')
engineApplyShaderToWorldTexture(shader, 'grassshort2long256')
engineApplyShaderToWorldTexture(shader, 'grassdeep256')
engineApplyShaderToWorldTexture(shader, 'forestfloor4')
engineApplyShaderToWorldTexture(shader, 'grasstype3dirt')
engineApplyShaderToWorldTexture(shader, 'grassdeep256')
engineApplyShaderToWorldTexture(shader, 'grass_lawn_128hv')
engineApplyShaderToWorldTexture(shader, 'tenniscourt1_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinsideblend2_256')
engineApplyShaderToWorldTexture(shader, 'hiwayblend1_256')
engineApplyShaderToWorldTexture(shader, 'desegravelgrassroadla')
engineApplyShaderToWorldTexture(shader, 'dirtblendlit')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrssdrt01')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrass01')
engineApplyShaderToWorldTexture(shader, 'golf_greengrass')
engineApplyShaderToWorldTexture(shader, 'golf_fairway3')
engineApplyShaderToWorldTexture(shader, 'golf_fairway1')
engineApplyShaderToWorldTexture(shader, 'golf_heavygrass')
engineApplyShaderToWorldTexture(shader, 'golf_hvygras_cpark')
engineApplyShaderToWorldTexture(shader, 'grass_dirt_64hv')
engineApplyShaderToWorldTexture(shader, 'grassdead1blnd')
engineApplyShaderToWorldTexture(shader, 'pavebsandend')
engineApplyShaderToWorldTexture(shader, 'grass_dry_64hv')
engineApplyShaderToWorldTexture(shader, 'grassdeadbrn256')
engineApplyShaderToWorldTexture(shader, 'grass10_stones256')
engineApplyShaderToWorldTexture(shader, 'sjmlahus28')
engineApplyShaderToWorldTexture(shader, 'sjmscorclawn3')
engineApplyShaderToWorldTexture(shader, 'grasstype510')
engineApplyShaderToWorldTexture(shader, 'grasstype510_10')
engineApplyShaderToWorldTexture(shader, 'desmudgrass')
engineApplyShaderToWorldTexture(shader, 'grass10dirt')
engineApplyShaderToWorldTexture(shader, 'roadblendcunt')
engineApplyShaderToWorldTexture(shader, 'ws_patchygravel')
engineApplyShaderToWorldTexture(shader, 'brngrss2stones')
engineApplyShaderToWorldTexture(shader, 'grasstype4-3')
engineApplyShaderToWorldTexture(shader, 'grasstype3')
engineApplyShaderToWorldTexture(shader, 'grasstype5_desdirt')
engineApplyShaderToWorldTexture(shader, 'dirtkb_64hv')
engineApplyShaderToWorldTexture(shader, 'desertgryard256grs2')
engineApplyShaderToWorldTexture(shader, 'des_dirt2grass')
engineApplyShaderToWorldTexture(shader, 'des_dirt1')
engineApplyShaderToWorldTexture(shader, 'grass')
engineApplyShaderToWorldTexture(shader, 'pavemiddirt_law')
engineApplyShaderToWorldTexture(shader, 'hllblf2_lae')
engineApplyShaderToWorldTexture(shader, 'forestfloorgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_glfhvy')
engineApplyShaderToWorldTexture(shader, 'hiwayinside5_256')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_grass')
engineApplyShaderToWorldTexture(shader, 'grass_128hv')
engineApplyShaderToWorldTexture(shader, 'ffbranch_mountdirt')
engineApplyShaderToWorldTexture(shader, 'desmud2forstfloor')
engineApplyShaderToWorldTexture(shader, 'forestfloorblend')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt2forest')
engineApplyShaderToWorldTexture(shader, 'rocktbrn128blnd')
engineApplyShaderToWorldTexture(shader, 'forest_rocks')
engineApplyShaderToWorldTexture(shader, 'desmud')
engineApplyShaderToWorldTexture(shader, 'grass10dirt')
engineApplyShaderToWorldTexture(shader, 'con2sand1b')
engineApplyShaderToWorldTexture(shader, 'vgsroadirt1_256')
engineApplyShaderToWorldTexture(shader, 'vgsroadirt2_256')
engineApplyShaderToWorldTexture(shader, 'con2sand1a')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn_grn')
engineApplyShaderToWorldTexture(shader, 'des_dirt2gygrass')
engineApplyShaderToWorldTexture(shader, 'ws_traingravelblend')
engineApplyShaderToWorldTexture(shader, 'sw_stones')
engineApplyShaderToWorldTexture(shader, 'sw_sand')
engineApplyShaderToWorldTexture(shader, 'sw_crops')
engineApplyShaderToWorldTexture(shader, 'newcrop3')
engineApplyShaderToWorldTexture(shader, 'sjmscorclawn')
engineApplyShaderToWorldTexture(shader, 'dirtgaz64b')
engineApplyShaderToWorldTexture(shader, 'bow_church_grass_gen')
engineApplyShaderToWorldTexture(shader, 'hiwayinside4_256')
engineApplyShaderToWorldTexture(shader, 'grasstype10_4blend')
engineApplyShaderToWorldTexture(shader, 'forestfloor256_blenddirt')
engineApplyShaderToWorldTexture(shader, 'desertstones256forestmix')
engineApplyShaderToWorldTexture(shader, 'dirt64b2')
engineApplyShaderToWorldTexture(shader, 'grifnewtex1x_las')
engineApplyShaderToWorldTexture(shader, 'grassdry_128hv')
engineApplyShaderToWorldTexture(shader, 'grass4dirtytrans')
engineApplyShaderToWorldTexture(shader, 'bow_church_dirt')
engineApplyShaderToWorldTexture(shader, 'grasstype5_4')
engineApplyShaderToWorldTexture(shader, 'sw_grass01a')
engineApplyShaderToWorldTexture(shader, 'sw_grassb01')
engineApplyShaderToWorldTexture(shader, 'sw_grass01d')
engineApplyShaderToWorldTexture(shader, 'sw_dirt01')
engineApplyShaderToWorldTexture(shader, 'sfn_rocktbrn128')
engineApplyShaderToWorldTexture(shader, 'sfn_rockhole')
engineApplyShaderToWorldTexture(shader, 'sfncn_rockgrass3')
engineApplyShaderToWorldTexture(shader, 'sfn_grass1')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixbmp')
engineApplyShaderToWorldTexture(shader, 'grasstype4')
engineApplyShaderToWorldTexture(shader, 'grasstype4_forestblend')
engineApplyShaderToWorldTexture(shader, 'forestfloor256')
engineApplyShaderToWorldTexture(shader, 'grasstype4_10')
engineApplyShaderToWorldTexture(shader, 'grasstype10')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmix_grass4')
engineApplyShaderToWorldTexture(shader, 'grass4dirty')
engineApplyShaderToWorldTexture(shader, 'dt_road2grasstype4')
engineApplyShaderToWorldTexture(shader, 'sw_grass01')
engineApplyShaderToWorldTexture(shader, 'grassdead1')
engineApplyShaderToWorldTexture(shader, 'bow_church_grass_alt')
engineApplyShaderToWorldTexture(shader, 'desertstones256')
engineApplyShaderToWorldTexture(shader, 'forestfloorblendded')
engineApplyShaderToWorldTexture(shader, 'grasstype4blndtodirt')
engineApplyShaderToWorldTexture(shader, 'grasstype4_mudblend')
engineApplyShaderToWorldTexture(shader, 'desertgryard256')
engineApplyShaderToWorldTexture(shader, 'desgreengrassmix')
engineApplyShaderToWorldTexture(shader, 'desertgravelgrass256')
engineApplyShaderToWorldTexture(shader, 'sw_stonesgrass')
engineApplyShaderToWorldTexture(shader, 'desgreengrass')
 engineApplyShaderToWorldTexture(shader, 'yardgrass1') 
 engineApplyShaderToWorldTexture(shader, 'grassgrnbrn256') 
 engineApplyShaderToWorldTexture(shader, 'des_grass2scrub') 
 engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1b') 
 engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1a') 
 engineApplyShaderToWorldTexture(shader, 'vgs_rockbot1a') 
 engineApplyShaderToWorldTexture(shader, 'vgs_rockmid1a') 
engineApplyShaderToWorldTexture(shader, 'des_ripplsand')
engineApplyShaderToWorldTexture(shader, 'des_rocky1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1')
engineApplyShaderToWorldTexture(shader, 'desstones_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_dirt2dedgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt2')
engineApplyShaderToWorldTexture(shader, 'des_dirtgravel')
engineApplyShaderToWorldTexture(shader, 'des_dirt2blend')
engineApplyShaderToWorldTexture(shader, 'des_rocky1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge2')
engineApplyShaderToWorldTexture(shader, 'des_panelconc')
engineApplyShaderToWorldTexture(shader, 'des_oldrunwayblend')
engineApplyShaderToWorldTexture(shader, 'desertstones256')
engineApplyShaderToWorldTexture(shader, 'grasstype5')
engineApplyShaderToWorldTexture(shader, 'grasstype5_dirt')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn')
engineApplyShaderToWorldTexture(shader, 'des_grass2dirt1')
engineApplyShaderToWorldTexture(shader, 'des_yelrock')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt')
engineApplyShaderToWorldTexture(shader, 'hiway2sand1a')
engineApplyShaderToWorldTexture(shader, 'hiwaygravel1_256')
engineApplyShaderToWorldTexture(shader, 'hiwaygravel1_lod')
engineApplyShaderToWorldTexture(shader, 'hiwayinside2_256')
engineApplyShaderToWorldTexture(shader, 'des_oldrunway')
engineApplyShaderToWorldTexture(shader, 'ws_rotten_concrete1')
engineApplyShaderToWorldTexture(shader, 'cw2_mountrock')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirtscree')
engineApplyShaderToWorldTexture(shader, 'grass4_des_dirt2')
engineApplyShaderToWorldTexture(shader, 'forestfloorbranch256')
engineApplyShaderToWorldTexture(shader, 'forestfloor3')
engineApplyShaderToWorldTexture(shader, 'des_dirt2grgrass')
engineApplyShaderToWorldTexture(shader, 'forestfloor3_forest')
engineApplyShaderToWorldTexture(shader, 'forestfloor_sones256')
engineApplyShaderToWorldTexture(shader, 'sw_sandgrass')
engineApplyShaderToWorldTexture(shader, 'sw_sandgrass4')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb1')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrass1')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb2')
engineApplyShaderToWorldTexture(shader, 'des_dirt2 trackl')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixb')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixc')
engineApplyShaderToWorldTexture(shader, 'desertstones256grass')
engineApplyShaderToWorldTexture(shader, 'desmuddesgrsblend')
engineApplyShaderToWorldTexture(shader, 'hiwayinsideblend3_256')
engineApplyShaderToWorldTexture(shader, 'grasslong256')
engineApplyShaderToWorldTexture(shader, 'sf_garden3')
engineApplyShaderToWorldTexture(shader, 'golfcourselod_sfs_b')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/5.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'tar_venturasjoin')
engineApplyShaderToWorldTexture(shader, 'crossing_law')
engineApplyShaderToWorldTexture(shader, 'desert_1linetar')
engineApplyShaderToWorldTexture(shader, 'desert_1line256')
engineApplyShaderToWorldTexture(shader, 'dt_roadblend')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvgtravel')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvlightsand')
engineApplyShaderToWorldTexture(shader, 'snpdwargrn1')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblenddrtdot')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblenddrt')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblend2')
engineApplyShaderToWorldTexture(shader, 'tar_freewyleft')
engineApplyShaderToWorldTexture(shader, 'tar_freewyright')
engineApplyShaderToWorldTexture(shader, 'tar_lineslipway')
engineApplyShaderToWorldTexture(shader, 'lod_des_road1')
engineApplyShaderToWorldTexture(shader, 'des_1line256')
engineApplyShaderToWorldTexture(shader, 'des_1lineend')
engineApplyShaderToWorldTexture(shader, 'des_1linetar')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hv')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblend')
engineApplyShaderToWorldTexture(shader, 'roaddgrassblnd')
engineApplyShaderToWorldTexture(shader, 'tar_1linefreewy')

end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/20.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrng2')
engineApplyShaderToWorldTexture(shader, 'mudyforest256')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc2')
engineApplyShaderToWorldTexture(shader, 'mountainskree_stones256')
engineApplyShaderToWorldTexture(shader, 'rocktq128blender')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'des_dirt2trackr')
engineApplyShaderToWorldTexture(shader, 'carpark_128')
engineApplyShaderToWorldTexture(shader, 'sf_pave2')
engineApplyShaderToWorldTexture(shader, 'stones256128')
engineApplyShaderToWorldTexture(shader, 'bow_abpave_gen')
engineApplyShaderToWorldTexture(shader, 'sf_pave3')
engineApplyShaderToWorldTexture(shader, 'macpath_lae')
engineApplyShaderToWorldTexture(shader, 'sf_pave5')
engineApplyShaderToWorldTexture(shader, 'drvin_ground1')
engineApplyShaderToWorldTexture(shader, 'obhilltex1')
engineApplyShaderToWorldTexture(shader, 'des_dustconc')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'cos_hiwayout_256')
engineApplyShaderToWorldTexture(shader, 'con2sand1c')
engineApplyShaderToWorldTexture(shader, 'hiwayinside3_256')
engineApplyShaderToWorldTexture(shader, 'hiwayoutside_256')
engineApplyShaderToWorldTexture(shader, 'concretedust2_256128')
engineApplyShaderToWorldTexture(shader, 'stormdrain6')
engineApplyShaderToWorldTexture(shader, 'des_dirt2stones')
engineApplyShaderToWorldTexture(shader, 'vgs_rockwall01_128')
engineApplyShaderToWorldTexture(shader, 'des_dam_wall')
engineApplyShaderToWorldTexture(shader, 'sandgrnd128')
engineApplyShaderToWorldTexture(shader, 'vgs_shopwall01_128')
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrn')
engineApplyShaderToWorldTexture(shader, 'parking2plain')
engineApplyShaderToWorldTexture(shader, 'parking2')
engineApplyShaderToWorldTexture(shader, 'rocktbrn128')
engineApplyShaderToWorldTexture(shader, 'rocktbrn128blndlit')
engineApplyShaderToWorldTexture(shader, 'cuntroad01_law')
engineApplyShaderToWorldTexture(shader, 'fancy_slab128')
engineApplyShaderToWorldTexture(shader, 'cst_rock_coast_sfw')
engineApplyShaderToWorldTexture(shader, 'venturas_fwend')
engineApplyShaderToWorldTexture(shader, 'desgrasandblend')
engineApplyShaderToWorldTexture(shader, 'cw2_mounttrailblank')
engineApplyShaderToWorldTexture(shader, 'rocktq128_forestblend2')
engineApplyShaderToWorldTexture(shader, 'rocktq128')
engineApplyShaderToWorldTexture(shader, 'desclifftypebs')
engineApplyShaderToWorldTexture(shader, 'cs_rockdetail2')
engineApplyShaderToWorldTexture(shader, 'cuntbrnclifftop')
engineApplyShaderToWorldTexture(shader, 'cuntbrncliffbtmbmp')
engineApplyShaderToWorldTexture(shader, 'cunt_botrock')
engineApplyShaderToWorldTexture(shader, 'stones256')
engineApplyShaderToWorldTexture(shader, 'grasstype4blndtomud')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/73.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'waterclear256')
engineApplyShaderToWorldTexture(shader, 'newaterfal1_256')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/40.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sm_bark_light')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/35.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'cloudmasked')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/21.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'rocktq128_dirt')
engineApplyShaderToWorldTexture(shader, 'newrockgrass_sfw')
engineApplyShaderToWorldTexture(shader, 'rocktq128_forestblend')
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrng')
engineApplyShaderToWorldTexture(shader, 'desclifftypebsmix')
engineApplyShaderToWorldTexture(shader, 'lasclifface')
engineApplyShaderToWorldTexture(shader, 'des_dirt1grass')
engineApplyShaderToWorldTexture(shader, 'cunt_toprock')
engineApplyShaderToWorldTexture(shader, 'desertgravelgrassroad')
engineApplyShaderToWorldTexture(shader, 'rocktq128_grass4blend')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/13.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_freeway3blend')
engineApplyShaderToWorldTexture(shader, 'ws_freeway3')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad2_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad3_256')
engineApplyShaderToWorldTexture(shader, 'sf_road5')
engineApplyShaderToWorldTexture(shader, 'sf_junction5')
engineApplyShaderToWorldTexture(shader, 'vegastriproad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad2_256')
engineApplyShaderToWorldTexture(shader, 'hiwayend_256')
engineApplyShaderToWorldTexture(shader, 'hiwaymidlle_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad1_256')
engineApplyShaderToWorldTexture(shader, 'cos_hiwaymid_256')
engineApplyShaderToWorldTexture(shader, 'sl_freew2road1')
engineApplyShaderToWorldTexture(shader, 'roadnew4_512')
engineApplyShaderToWorldTexture(shader, 'roadnew4_256')
engineApplyShaderToWorldTexture(shader, 'dt_road')
engineApplyShaderToWorldTexture(shader, 'sl_roadbutt1')
engineApplyShaderToWorldTexture(shader, 'craproad1_lae')
engineApplyShaderToWorldTexture(shader, 'snpedtest1')
engineApplyShaderToWorldTexture(shader, 'roadnew4blend_256')
engineApplyShaderToWorldTexture(shader, 'snpedtest1blend')
engineApplyShaderToWorldTexture(shader, 'craproad7_lae7')
end
)


addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/24.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_crackeddirt1')
engineApplyShaderToWorldTexture(shader, 'des_redrock1')
engineApplyShaderToWorldTexture(shader, 'des_redrock2')
engineApplyShaderToWorldTexture(shader, 'cw2_mounttrail')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/81.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'greyground256sand')
engineApplyShaderToWorldTexture(shader, 'boardwalk_la')
engineApplyShaderToWorldTexture(shader, 'indund_64')
engineApplyShaderToWorldTexture(shader, 'rodeo3sjm')
engineApplyShaderToWorldTexture(shader, 'gb_nastybar08')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvtodirt')
engineApplyShaderToWorldTexture(shader, 'dirttracksgrass256')
engineApplyShaderToWorldTexture(shader, 'grifnewtex1b')
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1r') -- ид текстурки 
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/53.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, '53.png"')

end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/32.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sw_farmroad01')
engineApplyShaderToWorldTexture(shader, 'desmudtrail2')
engineApplyShaderToWorldTexture(shader, 'desmudtrail3')
engineApplyShaderToWorldTexture(shader, 'cw2_weeroad1')
engineApplyShaderToWorldTexture(shader, 'dirttracksforest')
engineApplyShaderToWorldTexture(shader, 'desmudtrail')
engineApplyShaderToWorldTexture(shader, 'dirttracksgrass256')
end
)


addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/33.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'desgreengrasstrckend')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/18.png')
dxSetShaderValue(shader, 'gTexture', terrain)
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/78.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_alley_conc1')
engineApplyShaderToWorldTexture(shader, 'beachwalk_law')
engineApplyShaderToWorldTexture(shader, 'boardgate_law')
engineApplyShaderToWorldTexture(shader, 'stormdrain4_nt')
engineApplyShaderToWorldTexture(shader, 'studwalltop_law')
engineApplyShaderToWorldTexture(shader, 'block')
engineApplyShaderToWorldTexture(shader, 'stormdrain2_nt')
engineApplyShaderToWorldTexture(shader, 'block2')
engineApplyShaderToWorldTexture(shader, 'highshopwall1256')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc')
engineApplyShaderToWorldTexture(shader, 'concreteblock_256')
engineApplyShaderToWorldTexture(shader, 'stormdrain5_nt')
engineApplyShaderToWorldTexture(shader, 'stonewall2_la')
engineApplyShaderToWorldTexture(shader, 'ws_freeway2')
engineApplyShaderToWorldTexture(shader, 'des_facmetal')
engineApplyShaderToWorldTexture(shader, 'des_factower')
engineApplyShaderToWorldTexture(shader, 'des_facmetalsoild')
engineApplyShaderToWorldTexture(shader, 'block2_high')
engineApplyShaderToWorldTexture(shader, 'des_dam_conc')
engineApplyShaderToWorldTexture(shader, 'ws_woodenscreen1')
engineApplyShaderToWorldTexture(shader, 'concretewall22_256')
engineApplyShaderToWorldTexture(shader, 'pinkpave')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/79.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, '64322938')
engineApplyShaderToWorldTexture(shader, 'sl_pavebutt1')
engineApplyShaderToWorldTexture(shader, 'hilcouwall2')
engineApplyShaderToWorldTexture(shader, 'bow_smear_cement')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn4')
engineApplyShaderToWorldTexture(shader, 'backalley1_lae')
engineApplyShaderToWorldTexture(shader, 'sidewgrass4')
engineApplyShaderToWorldTexture(shader, 'sidewgrass3')
engineApplyShaderToWorldTexture(shader, 'sidewgrass_fuked')
engineApplyShaderToWorldTexture(shader, 'sidewgrass5')
engineApplyShaderToWorldTexture(shader, 'sidewgrass2')
engineApplyShaderToWorldTexture(shader, 'sidewgrass1')
engineApplyShaderToWorldTexture(shader, 'grassdry_path_128hv')
engineApplyShaderToWorldTexture(shader, 'grass_concpath2')
engineApplyShaderToWorldTexture(shader, 'laroad_offroad1')
engineApplyShaderToWorldTexture(shader, 'trainground3')
engineApplyShaderToWorldTexture(shader, 'ws_nicepave')
engineApplyShaderToWorldTexture(shader, 'nicepavegras_la')
engineApplyShaderToWorldTexture(shader, 'sidelatino1_lae')
engineApplyShaderToWorldTexture(shader, 'hiwayinside_256')
engineApplyShaderToWorldTexture(shader, 'blendpavement2b_256')
engineApplyShaderToWorldTexture(shader, 'blendpavement2_256')
engineApplyShaderToWorldTexture(shader, 'vegaspavement2_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave2_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypaveblend1')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypaveblend2')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn42')
engineApplyShaderToWorldTexture(shader, 'dockpave_256')
engineApplyShaderToWorldTexture(shader, 'pierplanks_128')
engineApplyShaderToWorldTexture(shader, 'sf_pave6')
engineApplyShaderToWorldTexture(shader, 'newpavement')
engineApplyShaderToWorldTexture(shader, 'ws_oldpainted2')
engineApplyShaderToWorldTexture(shader, 'stonesandkb2_128')
engineApplyShaderToWorldTexture(shader, 'sf_pave4')
engineApplyShaderToWorldTexture(shader, 'sidewalk4_lae')
engineApplyShaderToWorldTexture(shader, 'cos_hiwayins_256')
engineApplyShaderToWorldTexture(shader, 'pavebsand256')
engineApplyShaderToWorldTexture(shader, 'kbpavementblend')
engineApplyShaderToWorldTexture(shader, 'kbpavement_test')
engineApplyShaderToWorldTexture(shader, 'sl_pavebutt2')
engineApplyShaderToWorldTexture(shader, 'laroad_centre1')
engineApplyShaderToWorldTexture(shader, 'craproad5_lae')
engineApplyShaderToWorldTexture(shader, 'craproad6_lae')
engineApplyShaderToWorldTexture(shader, 'pavebsand256grassblended')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn41')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn42b')
engineApplyShaderToWorldTexture(shader, 'easykerb')
engineApplyShaderToWorldTexture(shader, 'sandypath_law')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/14.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_traintrax1')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/15.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'trainground2')
engineApplyShaderToWorldTexture(shader, 'concrete_64hv')
engineApplyShaderToWorldTexture(shader, 'concretenewb256')
engineApplyShaderToWorldTexture(shader, 'conchev_64hv')
engineApplyShaderToWorldTexture(shader, 'rail_stones256')
engineApplyShaderToWorldTexture(shader, 'sw_traingravelb1')
engineApplyShaderToWorldTexture(shader, 'ws_traingravel')
engineApplyShaderToWorldTexture(shader, 'heliconcrete')
engineApplyShaderToWorldTexture(shader, 'metpat64')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/3.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_redrockmid')
engineApplyShaderToWorldTexture(shader, 'rockwall2_lae2')
engineApplyShaderToWorldTexture(shader, 'rocktbrn_dirt2')
engineApplyShaderToWorldTexture(shader, 'rock_country128')
engineApplyShaderToWorldTexture(shader, 'golf_grassrock')
end
)


addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/face.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'cj_ped_head')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/34.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'txgrass0_1')
engineApplyShaderToWorldTexture(shader, 'sm_des_bush1')
engineApplyShaderToWorldTexture(shader, 'sm_des_bush2')
engineApplyShaderToWorldTexture(shader, 'sm_des_bush3')
engineApplyShaderToWorldTexture(shader, 'txgrass1_1')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/4.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_redrockbot')
engineApplyShaderToWorldTexture(shader, 'rockwall1_lae2')
engineApplyShaderToWorldTexture(shader, 'blendrock2grgrass')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/19.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirttrackx')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/64.png')
dxSetShaderValue(shader, 'gTexture', terrain) 
--engineApplyShaderToWorldTexture(shader, 'ws_castironwalk')
engineApplyShaderToWorldTexture(shader, 'ws_rottenwall')
engineApplyShaderToWorldTexture(shader, 'ws_sandstone1')
engineApplyShaderToWorldTexture(shader, 'ws_altz_wall10')
engineApplyShaderToWorldTexture(shader, '3a516e58')
engineApplyShaderToWorldTexture(shader, 'sam_camo')
engineApplyShaderToWorldTexture(shader, 'mp_brick_128')
engineApplyShaderToWorldTexture(shader, 'mp_guardtowerthin_128')
engineApplyShaderToWorldTexture(shader, 'bonyrd_skin2')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/concrete_21.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'rodeo3sjm')
engineApplyShaderToWorldTexture(shader, 'dt_road_stoplinea')
engineApplyShaderToWorldTexture(shader, 'plaintarmac1')
engineApplyShaderToWorldTexture(shader, 'ston_asfalt_iov_old_01')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc3')
engineApplyShaderToWorldTexture(shader, 'ws_tunnelwall2')
engineApplyShaderToWorldTexture(shader, 'ws_airpt_concrete')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/ws_wangcar1.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_wangcar1')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/ws_wangcar2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_wangcar2')
end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/tree19Mi.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'tree19Mi')
engineApplyShaderToWorldTexture(shader, 'newtreeleaves128')
engineApplyShaderToWorldTexture(shader, 'newtreed256')
end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/treeleaves1.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'treeleaves1')

end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/txgrassbig0.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'txgrassbig0')
end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/txgrassbig1.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'txgrassbig1')
end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/bloodpool_64a.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'bloodpool_64a')
end
)
--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2123213.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
end
)

--
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/image022.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'bonyrd_skin1')
engineApplyShaderToWorldTexture(shader, 'redmetal')
engineApplyShaderToWorldTexture(shader, 'des_bytower1')
engineApplyShaderToWorldTexture(shader, 'alumox64')
engineApplyShaderToWorldTexture(shader, 'rusta256128')
engineApplyShaderToWorldTexture(shader, 'block2_low')
engineApplyShaderToWorldTexture(shader, 'dish_panel_a')
engineApplyShaderToWorldTexture(shader, 'dish_panel_b')
engineApplyShaderToWorldTexture(shader, 'dish_roundbit_a')
engineApplyShaderToWorldTexture(shader, 'dish_panel_c')
engineApplyShaderToWorldTexture(shader, 'metal1_128')
engineApplyShaderToWorldTexture(shader, 'des_plyon1')
end
)

-- чилиад
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/22.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'golf_gravelpath')
engineApplyShaderToWorldTexture(shader, 'grass_path_128hv')
engineApplyShaderToWorldTexture(shader, 'des_quarryrd')
engineApplyShaderToWorldTexture(shader, 'des_quarryrdr')
engineApplyShaderToWorldTexture(shader, 'des_quarryrdl')
engineApplyShaderToWorldTexture(shader, 'cw2_mounttrail')
engineApplyShaderToWorldTexture(shader, 'cw2_mountroad')
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1')
engineApplyShaderToWorldTexture(shader, 'des_dirttrackl')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/52.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt2grass')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/58.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc3')
engineApplyShaderToWorldTexture(shader, 'dt_road_stoplinea')
engineApplyShaderToWorldTexture(shader, 'curb_64h')
engineApplyShaderToWorldTexture(shader, 'ws_whitewall2_bottom')
engineApplyShaderToWorldTexture(shader, 'plaintarmac1')
engineApplyShaderToWorldTexture(shader, 'greyground256')
engineApplyShaderToWorldTexture(shader, 'bow_abattoir_conc2')
engineApplyShaderToWorldTexture(shader, 'lasunion994')
engineApplyShaderToWorldTexture(shader, 'crossing_law2')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/98.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sandnew_law')
end
)


addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/42.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'elm_treegrn2')
end
)